### ISSUE TITLE
文件放进去了, 重启后不生效

### ISSUE THREAD

**Issue by xuechaoke** [liuze0109/Royal_TSX_Chinese_Language_Pack#4]
<img width="549" alt="image" src="https://user-images.githubusercontent.com/37655156/218403673-a9ffb10d-4acf-4df9-8b01-42069c2d8984.png">

<img width="527" alt="image" src="https://user-images.githubusercontent.com/37655156/218403608-211789ee-f27d-4b33-84d7-5a9c8a297269.png">
只有这个有点中文
<img width="883" alt="image" src="https://user-images.githubusercontent.com/37655156/218403810-ee0cb077-51b8-4bb8-91d2-d8df9ae22287.png">

**Comment by liuze0109** [comment]
zh_Hans.lproj 是一个文件夹，不是文件。另外，这个项目提供了一个shell自动汉化脚本，可以试试。
